apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webdeploy
  name: webdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdeploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webdeploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}

---

