apiVersion: batch/v1 # Notice the api here that is different from one for deployment.
kind: Job
metadata:
 name: sleepyjob
spec:
 parallelism: 1
 completions: 1
 template:
  spec:
   containers:
   - name: busybox
     image: busybox
     command: ["sleep"]
     args: ["10"] # sleep for 10 seconds and then exit
   restartPolicy: OnFailure